---
Name: locator
---
Dynamic\Locator\Model\Location:
  extensions:
    - Dynamic\SilverStripeGeocoder\DistanceDataExtension
    - Dynamic\SilverStripeGeocoder\AddressDataExtension
    - SilverStripe\Versioned\Versioned('Stage','Live')

Dynamic\Locator\Page\LocationPage:
  extensions:
    - LittleGiant\CatalogManager\Extensions\CatalogPageExtension
    - Dynamic\SilverStripeGeocoder\DistanceDataExtension
    - Dynamic\SilverStripeGeocoder\AddressDataExtension
  parent_classes:
    - Dynamic\Locator\Page\Locator
  sort_column: false
  automatic_live_sort: false
  show_in_sitetree: false

Dynamic\Locator\Page\Locator:
  infoWindowTemplate: 'dynamic/silverstripe-locator: client/infowindow-description.html'
  listTemplate: 'dynamic/silverstripe-locator: client/location-list-description.html'
  limit: 50
  show_radius: true
  radius_var: 'Radius'
  category_var: 'CategoryID'
  extensions:
    - SilverStripe\Lumberjack\Model\Lumberjack

---
Name: modules-locator
After: modules-other
Before: modules-framework
---
SilverStripe\Core\Manifest\ModuleManifest:
  module_priority:
    - dynamic/silverstripe-locator
