---
Name: locator
---
Dynamic\Locator\Location:
  extensions:
    - Dynamic\SilverStripeGeocoder\DistanceDataExtension
    - Dynamic\SilverStripeGeocoder\AddressDataExtension
    - SilverStripe\Versioned\Versioned('Stage','Live')
